version: "2"
services:
  apache:
    restart: always
    image: httpd:2.4
    ports:
      - "82:80"
    volumes:
      - /var/www:/usr/local/apache2/htdocs/


  goahead:
    restart: always
    build: ./goahead/
    ports:
      - "83:80"
    volumes:                                                                                                            
      - /var/www:/var/www
